# vim:set ft=tmux:
%hidden MODULE_NAME="cpu"


set -gq "@catppuccin_${MODULE_NAME}_icon" " "
set -gqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_fg" "#{E:@thm_fg}"
set -gqF "@catppuccin_status_${MODULE_NAME}_text_bg" "#{E:@catppuccin_status_module_text_bg}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(tmux-mem-cpu-load --interval 2 --averages-count 0 --graph-lines 0 | awk '{print $2}')"

source -F "#{d:current_file}/../plugins/catppuccin/tmux/utils/status_module.conf"
