# vim:set ft=tmux:
%hidden MODULE_NAME="ram"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰍛 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(tmux-mem-cpu-load --interval 2 --averages-count 0 --graph-lines 0 | awk '{print $1}')"

source -F "#{d:current_file}/../plugins/catppuccin/tmux/utils/status_module.conf"
